name: Check pull request source branch
on:
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize
jobs:
  check-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Print variables
        run: |
          echo "${{ github }}" | jq .
